services:
  hand_gesture_api:
    image: docker.io/scorpio1317/mlops_maze:latest  # Uses the published image from Docker Hub
    container_name: hand_gesture_api
    ports:
      - "8001:8000"  
    environment:
      - ENABLE_METRICS=true
      - MIN_CONFIDENCE_THRESHOLD=0.1
    restart: unless-stopped
    pull_policy: always  # Always pull latest version from Docker Hub

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped
    depends_on:
      - hand_gesture_api

  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    restart: unless-stopped
    depends_on:
      - prometheus