# prometheus.yml - Hand Gesture API Monitoring Configuration

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'hand-gesture-api-monitor'

# Scrape configurations
scrape_configs:
  - job_name: 'hand_gesture_api'
    static_configs:
      - targets: ['hand_gesture_api:8000']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 8s
    honor_labels: true
    params:

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    scrape_timeout: 20s

# Storage configuration
storage:
  tsdb:
    retention.time: 7d
    retention.size: 1GB