# prometheus.yml - Optimized for Hand Gesture API
global:
  scrape_interval: 15s      # Default scrape frequency
  evaluation_interval: 15s  # How often to evaluate rules
  external_labels:
    monitor: 'hand-gesture-api-monitor'

# Scrape configurations
scrape_configs:
  # Hand Gesture API - More frequent monitoring for ML metrics
  - job_name: 'hand_gesture_api'
    static_configs:
      - targets: ['hand_gesture_api:8000']
    metrics_path: /metrics
    scrape_interval: 10s     # Every 10 seconds (good for demo/testing)
    scrape_timeout: 8s       # 80% of scrape_interval (safe margin)
    honor_labels: true

  # Prometheus self-monitoring - Less frequent is fine
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s     # Every 30 seconds (Prometheus doesn't change much)
    scrape_timeout: 10s      # 33% of scrape_interval (safe)